from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

def serialize_pdf(records: list[dict]) -> bytes:
    """
    Serializes a list of dictionaries into a PDF byte stream using reportlab.
    Handles empty list case by returning an empty byte string.
    """
    if not records:
        return b""

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()

    # Add a Title to the PDF
    elements.append(Paragraph("Data Export", styles['Title']))
    elements.append(Paragraph("Generated by Hermes Agent", styles['Normal']))

    # Prepare Table Data
    # Get headers from the first record
    headers = list(records[0].keys())
    data = [headers]

    # Build rows
    for record in records:
        row = [str(record.get(h, "")) for h in headers]
        data.append(row)

    # Create and style the table
    table = Table(data)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.dodgerblue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    
    elements.append(table)
    doc.build(elements)
    
    return buffer.getvalue()
